<?php
$data = array (
  866 => 
  array (
    'cat_id' => '866',
    'cat_name' => '蛋糕名录',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '866',
    'name' => '蛋糕名录',
  ),
  867 => 
  array (
    'cat_id' => '867',
    'cat_name' => '乳脂奶油蛋糕',
    'measure_unit' => '',
    'parent_id' => '866',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '867',
    'name' => '乳脂奶油蛋糕',
  ),
  869 => 
  array (
    'cat_id' => '869',
    'cat_name' => '乳酪蛋糕',
    'measure_unit' => '',
    'parent_id' => '866',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '869',
    'name' => '乳酪蛋糕',
  ),
  873 => 
  array (
    'cat_id' => '873',
    'cat_name' => '手工巧克力',
    'measure_unit' => '',
    'parent_id' => '866',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '873',
    'name' => '手工巧克力',
  ),
  870 => 
  array (
    'cat_id' => '870',
    'cat_name' => '巧克力蛋糕',
    'measure_unit' => '',
    'parent_id' => '866',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '870',
    'name' => '巧克力蛋糕',
  ),
  871 => 
  array (
    'cat_id' => '871',
    'cat_name' => '无糖蛋糕',
    'measure_unit' => '',
    'parent_id' => '866',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '871',
    'name' => '无糖蛋糕',
  ),
  868 => 
  array (
    'cat_id' => '868',
    'cat_name' => '慕斯蛋糕',
    'measure_unit' => '',
    'parent_id' => '866',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '868',
    'name' => '慕斯蛋糕',
  ),
  872 => 
  array (
    'cat_id' => '872',
    'cat_name' => '冰淇淋蛋糕',
    'measure_unit' => '',
    'parent_id' => '866',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '872',
    'name' => '冰淇淋蛋糕',
  ),
  874 => 
  array (
    'cat_id' => '874',
    'cat_name' => '产品推荐',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '874',
    'name' => '产品推荐',
  ),
);
?>